[workspace]
members = [
    "crates/layline",
    "crates/layline-core",
    "crates/layline-derive",
    "crates/layline-codegen",
]
resolver = "3"

[workspace.package]
version = "0.3.0"
edition = "2024"
rust-version = "1.88"
license = "MPL-2.0"
repository = "https://github.com/sachaw/layline"
homepage = "https://github.com/sachaw/layline"
documentation = "https://docs.rs/layline"
keywords = ["binary", "parsing", "bitfield", "protocol", "no-std"]
categories = ["encoding", "parser-implementations", "embedded", "no-std"]

[workspace.dependencies]
layline-core = { path = "crates/layline-core", version = "0.3.0", default-features = false }
layline-derive = { path = "crates/layline-derive", version = "0.3.0" }
